name: 'Terraform'

on: push

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.VERY_IMPORTANT_SECRET }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Expose secret
      run: |
        echo "$TEST_SECRET"
        echo "foobar"